sayanarijit/xplr

.github/workflows/cd.yml, .github/workflows/ci.yml, README.md, benches/navigation.rs, src/app.rs, src/config.rs, src/event_reader.rs, src/input.rs, src/lib.rs, src/main.rs, src/pipe_reader.rs, src/ui.rs
Mostly stolen from https://github.com/Rigellute/spotify-tui.
=> Add CI/CD gh actions

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, src/app.rs, src/auto_refresher.rs, src/config.rs, src/lib.rs, src/main.rs
- Auto `Refresh` every second.
- Add alias `BashExec` to message `Call` with args [`-c`, `bash` ...].
Also, Create alias `BashExec` to message `Call` with arguments [`bash`, `-c`]
=> Autorefresh, BashExec and basename

README.md
"it's" is an abbreviation for "it is".
"its" is a possessive pronoun meaning (e.g. "the ghost and its lunch box" or "the software and its features")
https://www.faa.gov/about/initiatives/plain_language/articles/its/
=> Update README.md: it's -> its

Cargo.toml, default.nix, src/app.rs
Hello,
I created a small `default.nix` file for your project so i could install it on my NixOS system (as it is not (yet) in nixpkgs).
If you are interested here it is !
Nix(OS) users can then install `xplr` with the following command:
```
nix-env -i -f https://github.com/sayanarijit/xplr/tarball/main
```
=> Add Default nix

Cargo.toml, benches/navigation.rs, default.nix, src/app.rs, src/event_reader.rs, src/main.rs, src/pipe_reader.rs
- Write to pipes only when the value changes.
- Sleep when not reading key event or messages.
Fixes: https://github.com/sayanarijit/xplr/issues/10
=> Several optimizations

src/config.rs
Fixes: https://github.com/sayanarijit/xplr/issues/11
=> Make dir colors cyan

Cargo.lock, Cargo.toml, benches/navigation.rs, src/app.rs, src/lib.rs, src/main.rs, src/pwd_watcher.rs
Also optimize the main thread.
=> Add pwd watcher

Cargo.lock, Cargo.toml, RELEASE.md, default.nix, src/config.rs, src/config.yml, src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/54
=> Improve scrolling behaviour

src/app.rs, src/config.yml, src/ui.rs
=> Better symlink support

Cargo.lock, Cargo.toml, src/config.rs, src/config.yml, src/ui.rs
Also, add `general.logs` to the config.
Ref: https://no-color.org/
=> Add support for NO_COLOR

src/config.rs, src/ui.rs, tests/test_config.rs, tests/test_ui.rs
This fixes the overwriting of default configuration.
Also, add tests to validate the new logic.
Fixes: #68
=> Fix overwriting of default config.

src/app.rs, src/config.yml
- SelectAll
- SelectPath
- UnSelectAll
- UnSelectPath
- ToggleSelectAll
- ToggleSelectionByPath
=> Add mode selection commands

src/config.rs, src/ui.rs
Fixes: https://github.com/sayanarijit/xplr/issues/68
=> Fix UI style priority

src/config.rs, src/config.yml
Use `f` to set relative path filter.
=> Add filter key binding

src/config.yml
=> Allow empty icons

src/app.rs, src/config.yml, src/input.rs
Add support proper implementations of -
- backspace
- ctrl-w
- ctrl-u
Also, improved sort and filter behavior.
Fixes: https://github.com/sayanarijit/xplr/issues/77
=> Improve key inputs

src/app.rs, src/config.yml, src/ui.rs
Fixes: https://github.com/sayanarijit/xplr/issues/81
=> Fix selection

src/app.rs, src/config.rs, src/config.yml
Ref: https://github.com/sayanarijit/xplr/issues/22
=> Add read-only mode

src/app.rs, src/config.rs, src/ui.rs
Do not include non-read-only actions in the in read-only mode. i.e. do
not display non-read-only actions in help menu.
Ref: https://github.com/sayanarijit/xplr/issues/22
=> Improve read-only mode

Cargo.lock, Cargo.toml, src/app.rs, src/config.yml, src/runner.rs, src/ui.rs
Also supports sorting by inode size.
Closes: https://github.com/sayanarijit/xplr/issues/84
=> Added inode size

src/config.rs, src/config.yml
Also improve the filter mode key bindings
Fixes: https://github.com/sayanarijit/xplr/issues/88
=> Fix ctrl-l breaking UI

src/app.rs, src/config.yml
Follow symlink to files to it's parent directory.
Also, hide file size for directories.
Ref: https://github.com/sayanarijit/xplr/issues/84
=> Follow file symlinks

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
While trying to enter restricted directories, log error instead or
exiting.
=> Do not exit on permission denial

src/event_reader.rs
Fixes: https://github.com/sayanarijit/xplr/issues/10
=> Improve CPU usage attempt 2

tests/unit/config.rs
Make sure https://github.com/sayanarijit/xplr/issues/97 hever happens
again.
=> Add test for config incompatibility error

Cargo.lock, Cargo.toml, src/config.rs, src/config.yml
Fixes: https://github.com/sayanarijit/xplr/issues/111
=> Fix distorted screen when opening files in GUI

Cargo.lock, Cargo.toml, src/config.rs, src/config.yml
Make it possible to create, delete, copy, move, rename filenames starting
with a - (hiphen).
=> Fix support for filenames starting with - (hiphen)

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
Let's not optimize things until we have tests.
=> Fix pipes not updating properly

src/config.yml
Adds ctrl-n and ctrl-p as rebinds for down and up inside of search mode, to improve usability.
=> Better usability in search mode

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
Also, use a better prompt symbol.
Ref: https://github.com/sayanarijit/xplr/issues/107
=> Add SwitchModeBuiltin and SwitchModeCustom

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
Also support toggle selection in search mode.
And use a pager to display logs.
=> Fix displaying global help menu

Cargo.toml, src/pwd_watcher.rs
Also improve the $PWD watcher logic.
=> Optimize release binary size

Cargo.lock, Cargo.toml, src/config.rs, src/config.yml
Stay in the current mode when key input is not recognised. It's better
to do nothing than doing something wrong, at least when dealing with
important files and folders.
=> Improve key bindings

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
Ref: https://github.com/sayanarijit/xplr/discussions/146#discussioncomment-741580
=> Add support for native lua bindings

Cargo.toml, src/app.rs
Ref: https://github.com/khvzak/mlua/issues/48
=> Add send+anyhow support for mlua

src/app.rs, src/runner.rs
Closes: https://github.com/sayanarijit/xplr/issues/163
=> Fix CallSilently

Cargo.lock, Cargo.toml, benches/criterion.rs, src/app.rs, src/config.rs, src/config.yml, src/default_config.rs, src/init.lua, src/lib.rs, src/lua.rs, src/main.rs, src/runner.rs, src/ui.rs
Replace handlebars with Lua functions by introduction Lua function API.
=> Replace handlebars with Lua

src/event_reader.rs, src/runner.rs
Mouse actions will be enabled on devices that support it.
=> Add optional mouse handler

src/app.rs, src/runner.rs
Make path history behave like jump list and allow jumping back and
forth in the same directory.
=> Improve history navigation

src/app.rs, src/pipe_reader.rs, src/runner.rs
With this change, xplr will delete the pipe files when command execution
is over.
=> Fix MacOS error directory not empty

src/app.rs
When the custom `init.lua` is corrupt, xplr will fall back to default
configuration, logging the encountered error after load.
=> Fall back to default config when custom config fails

Cargo.lock, Cargo.toml, src/init.lua, src/lua.rs
- Broken symlink should display without error.
- Display the symlink destination.
- Fix deleting symlinks pointing to a directory.
Fixes: https://github.com/sayanarijit/xplr/issues/185
=> Fix symlink handling

Cargo.lock, Cargo.toml, src/app.rs, src/init.lua, src/lib.rs, src/lua.rs, src/permissions.rs, src/ui.rs
Ref: https://github.com/sayanarijit/xplr/issues/187
=> Add colorful permissions

src/init.lua, src/ui.rs
Also, map ":q" to "quit" action.
Ref: https://github.com/sayanarijit/xplr/issues/158
=> Make mode visible in input/logs panel

src/init.lua
Sorry I realized how my comment was confusing, we needed one less space here, not one more 😅
=> Remove extra spaces

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/init.lua, src/lua.rs, src/runner.rs, src/ui.rs
Refs:
- https://github.com/sayanarijit/xplr/issues/187
- https://github.com/sayanarijit/xplr/issues/194
- https://github.com/sayanarijit/xplr/issues/195
=> Improve CallLua, mime_essence, permissions

Cargo.lock, Cargo.toml, src/config.rs, src/lua.rs, src/ui.rs
Inherit `node_types` config instead of overwriting it.
Closes: https://github.com/sayanarijit/xplr/issues/200
=> Inherit node types config

Cargo.lock, Cargo.toml, src/app.rs, src/lua.rs, src/runner.rs
Pass a custom table, optimized for convenience and speed.
=> Improve CallLua and CallLuaSilently

.github/workflows/daily-compile.yml
https://github.com/sayanarijit/xplr/issues/208 should never happen
again. This added check will notify me if `xplr` compilation starts
failing.
=> Check xplr compilation daily

examples/run.rs, src/app.rs, src/explorer.rs, src/lib.rs, src/main.rs, src/runner.rs
Minor improvements to the xplr library API.
Closes: https://github.com/sayanarijit/xplr/issues/213
=> Polish xplr library API

.github/workflows/cd.yml
Closes: https://github.com/sayanarijit/xplr/issues/212
=> Use --locked when releasing

src/app.rs, src/init.lua
Closes: https://github.com/sayanarijit/xplr/issues/207
=> No need to "Refresh" explicitly

Cargo.lock, Cargo.toml, benches/criterion.rs, src/event_reader.rs, src/init.lua, src/runner.rs
Closes: https://github.com/sayanarijit/xplr/issues/187
=> Upgrade dependencies

src/app.rs, src/explorer.rs, src/runner.rs
Fixes: https://github.com/sayanarijit/xplr/issues/211
=> Fix focus jumping

.github/workflows/cd.yml, Cargo.lock, Cargo.toml, src/lua.rs
Closes: https://github.com/sayanarijit/xplr/issues/131
=> Sign releases with pgp

src/app.rs, src/config.rs
Use `config.general.disable_recover_mode = true` to disable the recover
mode.
Closes: https://github.com/sayanarijit/xplr/issues/232
=> Add option to disable recover mode

src/bin/xplr.rs, src/config.rs, src/runner.rs
Closes: https://github.com/sayanarijit/xplr/issues/22
=> Support specifying read-only mode via CLI argument

Cargo.lock, Cargo.toml, src/app.rs, src/lua.rs
Fixes: https://github.com/sayanarijit/xplr/issues/249
=> Fix FocusPath issue

src/app.rs
Closes: https://github.com/sayanarijit/xplr/issues/255
=> Fix handling of relative paths

src/app.rs
Closes: https://github.com/sayanarijit/xplr/issues/253
=> Improve FocusNext and FocusPrevious behavior

src/event_reader.rs, src/runner.rs
Ref: https://github.com/sayanarijit/xplr/issues/10
=> Increase poll timeout

.github/workflows/book.yml, .gitignore, docs/en/book.toml, docs/en/src/SUMMARY.md, docs/en/src/alternatives.md, docs/en/src/community.md, docs/en/src/configuration.md, docs/en/src/configure.md, docs/en/src/contribute.md, docs/en/src/default-key-bindings.md, docs/en/src/general-config.md, docs/en/src/install.md, docs/en/src/introduction.md, docs/en/src/key-bindings.md, docs/en/src/layouts.md, docs/en/src/message.md, docs/en/src/modes.md, docs/en/src/post-install.md, docs/en/src/quickstart.md, docs/en/src/style.md, docs/en/src/todo.md, docs/en/src/upgrade-guide.md, docs/index.html
Closes: https://github.com/sayanarijit/xplr/issues/263
=> Publish xplr book with intensive documentation

src/config.rs, src/init.lua, src/runner.rs
Also add `xplr.config.general.start_fifo`.
Closes: https://github.com/sayanarijit/xplr/issues/280
=> Fix StartFifo and ToggleFifo

src/app.rs
Fixes: https://github.com/sayanarijit/xplr/issues/295
=> Fix ToggleSelectionByPath

src/app.rs, src/lua.rs, src/runner.rs
Fixes: https://github.com/sayanarijit/xplr/issues/284
Closes: https://github.com/sayanarijit/xplr/issues/286
Partially fixes: https://github.com/sayanarijit/xplr/issues/285
=> Minor improvements

src/runner.rs
Fixes: https://github.com/sayanarijit/xplr/issues/293
=> Recursively clean session path

benches/criterion.rs, src/app.rs, src/explorer.rs, src/runner.rs
Closes: https://github.com/sayanarijit/xplr/issues/289
=> Remove per directory buffer

examples/run.rs, src/app.rs, src/bin/xplr.rs, src/cli.rs, src/runner.rs
Some API improvements on top of #324
=> Improve runner API

src/config.rs, src/init.lua, src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/322
=> Add focus selection UI

docs/en/src/install.md
Closes: https://github.com/sayanarijit/xplr/issues/332
=> Always pass `--locked` when installing using cargo

.github/workflows/ci.yml, docs/en/src/general-config.md, src/app.rs, src/config.rs, src/init.lua
Closes: https://github.com/sayanarijit/xplr/issues/330
=> Disable recover mode by default

docs/en/src/layouts.md, docs/en/src/modes.md, src/app.rs, src/config.rs, src/init.lua, src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/335
=> Support defining custom layout for different modes

docs/en/src/message.md, src/app.rs
Closes: https://github.com/sayanarijit/xplr/issues/303
=> Support switching modes keeping input buffer.

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/event_reader.rs, src/lua.rs, src/runner.rs
Stop the thread instead of pausing it. This improves the CPU usage and
responsiveness a slightly.
=> Improve input reading by eliminating pause

src/runner.rs
=> Change to use `PWD` env vairable to get current dir

README.md, docs/en/src/SUMMARY.md, docs/en/src/configure-key-bindings.md, docs/en/src/debug-key-bindings.md, docs/en/src/default-key-bindings.md, docs/en/src/key-bindings.md, docs/en/src/message.md, docs/en/src/modes.md, docs/en/src/writing-plugins.md, docs/index.html, src/app.rs, src/config.rs, src/init.lua, src/input.rs
This PR adds 3 more keyboard input handlers:
- on_alphanumeric
- on_character
- on_navigation
Also updates documentation.
=> Add more keyboard input handlers

src/ui.rs
Fixes: https://github.com/sayanarijit/xplr/issues/396
=> Fix logs UI

docs/en/src/configure-key-bindings.md, docs/en/src/debug-key-bindings.md, src/app.rs, src/config.rs, src/input.rs
This adds `on_function` handler to handle F1-F12 keys.
This also fixes issues with previously added handlers and adds a
checklist for future additions.
=> Add on_function key handler

docs/index.html
Video contributed by @igorepst
Closes: https://github.com/sayanarijit/xplr/issues/389
=> Add demo video

src/lua.rs, src/runner.rs, src/ui.rs
Fixes: https://github.com/sayanarijit/xplr/issues/417
=> Serialize None to nil

snap/snapcraft.yaml
=> Add snap build

docs/en/src/default-key-bindings.md, docs/en/src/general-config.md, docs/en/src/modes.md, src/app.rs, src/config.rs, src/init.lua
Features:
- Display debug menu on configuration error
- Configure wether xplr should show the debug menu
(through `debug_on_error`)
- Open logs in editor
- Redirect people to the issues page on Github.
=> Debug mode

docs/en/src/default-key-bindings.md, src/app.rs, src/config.rs, src/init.lua
Closes https://github.com/sayanarijit/xplr/issues/434
=> Add "duplicate as"

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/lua.rs
- Upgrade rust to 1.58.1
- Upgrade rust edition to 2021
- Upgrade xplr packages
=> Upgrade version

Cargo.lock, Cargo.toml, docs/en/src/default-key-bindings.md, docs/en/src/filtering.md, docs/en/src/messages.md, docs/en/src/modes.md, src/app.rs, src/config.rs, src/init.lua, src/msg/in_/external.rs, src/runner.rs, src/ui.rs
- Add new regex filters
- `RelativePathDoesMatchRegex`
- `RelativePathDoesNotMatchRegex`
- `IRelativePathDoesMatchRegex`
- `IRelativePathDoesNotMatchRegex`
- `AbsolutePathDoesMatchRegex`
- `AbsolutePathDoesNotMatchRegex`
- `IAbsolutePathDoesMatchRegex`
- `IAbsolutePathDoesNotMatchRegex`
- Search mode now defaults to regex
- Added new message `SetInputPrompt` to set the input prompt
dynamically.
Closes: https://github.com/sayanarijit/xplr/pull/474
=> Add regex support and dynamic input prompt

src/bin/xplr.rs, src/cli.rs
- Use `--read0 -` to read `\0` separated paths from stdin.
- Use `--write0` to write `\0` separated paths to stdout.
- Use `-0` or `--null` to combine `--read0` and `--write0`.
Closes: https://github.com/sayanarijit/xplr/issues/472
=> Add support for null characters as separator

docs/en/src/awesome-plugins.md
I've updated my [plugin](https://github.com/dtomvan/extra-icons.xplr), so it's (hopefully) compatible with the themes and
other icon theme. So I figured I should add it to the list at this point.
=> Add dtomvan/extra-icons.xplr to awesome-plugins.md

src/msg/in_/external.rs
Compile regex once and reuse it.
=> Optimize regex search

src/msg/in_/external.rs
No need to compile both regex and iregex.
=> Optimize regex search further

Cargo.lock, Cargo.toml, src/app.rs, src/runner.rs, src/ui.rs
Ref: https://github.com/wez/wezterm/issues/2054
=> Be OSC 7 compliant

Cargo.lock, Cargo.toml, docs/en/src/column-renderer.md, docs/en/src/input-operation.md, src/app.rs, src/config.rs, src/event_reader.rs, src/input.rs, src/node.rs, src/ui.rs
Closes https://github.com/sayanarijit/xplr/pull/494
=> Parse file UID and GID

Cargo.lock, Cargo.toml, src/bin/xplr.rs, src/msg/in_/external.rs
Fixes https://github.com/sayanarijit/xplr/issues/503
=> Fix regex deserialization

docs/en/src/mode.md, src/app.rs, src/config.rs, src/init.lua
Closes: https://github.com/sayanarijit/xplr/issues/502
=> Custom input prompts for different modes without SetInputPrompt

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/app.rs, src/directory_buffer.rs, src/lua.rs
Fixes https://github.com/sayanarijit/xplr/issues/503
=> Fix directory explore scheduling

Cargo.lock, Cargo.toml, docs/en/src/awesome-plugins.md, docs/en/src/default-key-bindings.md, docs/en/src/general-config.md, docs/en/src/messages.md, docs/en/src/upgrade-guide.md, src/app.rs, src/config.rs, src/explorer.rs, src/init.lua, src/lua.rs, src/msg/in_/external.rs, src/node.rs, src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/496
Closes: https://github.com/sayanarijit/xplr/issues/500
=> Use fuzzy search instead of regex search

.github/workflows/cd.yml
=> Use external gzip for compressing the git source

Cargo.lock, Cargo.toml, src/ui.rs
Ref: https://github.com/sayanarijit/tui-input/pull/14
=> Fix displaying multispace characters

src/init.lua
Fixes: https://github.com/sayanarijit/xplr/issues/544
=> Fix creating file with spaces

src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/542
=> Hide counts if 0

docs/en/src/xplr.util.md, src/lua/util.rs
Closes: https://github.com/sayanarijit/xplr/issues/541
=> Implement xplr.util.to/from_json/yaml

docs/en/src/upgrade-guide.md, docs/en/src/xplr.util.md, src/lua/mod.rs, src/lua/util.rs
Closes: https://github.com/sayanarijit/xplr/issues/540
=> Implement xplr.util.version

src/init.lua
=> Launch $SHELL, fallback to bash

docs/en/src/configuration.md, src/app.rs, src/config.rs, src/init.lua
I think having a way for plugins to know when the mode or layout is changed can be quite useful, that's why I quickly added that, maybe it could have been done better, do as you please, greetings.
=> Add both hooks for Mode and Layout switch

docs/en/src/install.md, src/init.lua
Probably fixes: https://github.com/sayanarijit/xplr/issues/559
=> Fix file creation for mac's default bash

.github/workflows/cd.yml, .github/workflows/ci.yml, src/init.lua
Fixes: https://github.com/sayanarijit/xplr/issues/536
=> Fix visibility for light background

Cargo.lock, Cargo.toml, src/init.lua, src/lua/util.rs, src/ui.rs
Creating pull req against dev branch.
Closes: https://github.com/sayanarijit/xplr/pull/566
=> Add xplr.util.lscolor and xplr.util.paint

Cargo.lock, Cargo.toml, src/lua/util.rs, src/ui.rs
Adds the utility function xplr.util.wrap mentioned in #564.
I don't know if ui.rs was the best place to put the options struct, but I wasn't sure where else to put it.
=> Add utility function xplr.util.textwrap

src/lua/util.rs, src/ui.rs
Closes: https://github.com/sayanarijit/xplr/issues/573
=> Add xplr.util.layout_replaced

src/init.lua
- `:sl` to list selection.
- `:ss` to softlink.
- `:sh` to hardlink.
- Avoid conflict by adding suffix.
- Unselect individual path only on operation success.
Closes:
- https://github.com/sayanarijit/xplr/issues/572
- https://github.com/sayanarijit/xplr/issues/571
- https://github.com/sayanarijit/xplr/issues/570
=> Improve selection operations

docs/en/src/default-key-bindings.md, docs/en/src/xplr.util.md, src/app.rs, src/bin/xplr.rs, src/cli.rs, src/init.lua, src/input.rs, src/lua/mod.rs, src/lua/util.rs, src/path.rs, src/runner.rs, src/ui.rs
- Key binding ":se" to edit selection list in $EDITOR
- New utility functions:
- xplr.util.clone
- xplr.util.exists
- xplr.util.is_dir
- xplr.util.is_file
- xplr.util.is_symlink
- xplr.util.is_absolute
- xplr.util.path_split
- xplr.util.node
Closes: https://github.com/sayanarijit/xplr/issues/580
Closes: https://github.com/sayanarijit/xplr/issues/579
Closes: https://github.com/sayanarijit/xplr/issues/577
=> Add more features

docs/en/src/default-key-bindings.md, docs/en/src/messages.md, docs/en/src/xplr.util.md, src/app.rs, src/init.lua, src/lua/util.rs, src/msg/in_/external.rs
- FocusNextSelection      (ctrl-n)
- FocusPreviousSelection  (ctrl-p)
Also improve batch operations
=> Add selection navigation

benches/criterion.rs, docs/en/src/column-renderer.md, src/app.rs, src/lua/util.rs, src/node.rs
And handle application/x-executable mime type.
Closes: https://github.com/sayanarijit/xplr/issues/590
=> Add permissions in Resolved Node

src/init.lua
Refs:
- https://github.com/sayanarijit/xplr/issues/594
- https://github.com/sayanarijit/xplr/issues/559
=> Add workaround for macos with legacy coreutils

src/init.lua, src/lua/util.rs
Ref: https://github.com/sayanarijit/map.xplr/issues/4
=> Keep the selection list and clear manually

src/app.rs, src/explorer.rs, src/init.lua
Fixes: https://github.com/sayanarijit/xplr/issues/598
=> Fix broken history

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/lua/mod.rs, src/ui.rs
- SelectAll will not unselect the existing paths. Same for ToggleSelectAll.
- Fixed UI bug causing random bold characters (deps).
=> Fix SelectAll and UI colors

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/app.rs, src/lua/mod.rs, src/ui.rs
- SelectAll: extend selection list rather than replacing (#603)
- Fix SelectAll and UI colors (#604)
=> Release v0.21.1

docs/en/src/awesome-hacks.md, docs/en/src/awesome-plugins.md, docs/en/src/general-config.md, docs/en/src/layout.md, docs/en/src/lua-function-calls.md, docs/en/src/messages.md, docs/en/src/node_types.md, docs/en/src/searching.md, docs/en/src/upgrade-guide.md, src/bin/xplr.rs, src/init.lua, src/msg/in_/external.rs
=> Mostly documentation fixes

docs/en/src/post-install.md, src/init.lua
Use disown to keep the processs alive.
Fixes https://github.com/sayanarijit/xplr/issues/616
=> Send GUI processes to background

docs/en/src/awesome-hacks.md, src/init.lua
Fixes: https://github.com/sayanarijit/xplr/issues/620
=> Lower LS_COLORS priority

.codespellignore, .github/workflows/ci.yml
see https://github.com/sayanarijit/xplr/commit/8cca2d35669316bb672da73944fdbd595746b098
=> chore: added codespell to github ci

src/app.rs, src/config.rs, src/msg/in_/internal.rs
Also optimize navigation with selection items.
Refresh selection only when it's required.
Closes: https://github.com/sayanarijit/xplr/issues/635
=> Implement on_selection_change

docs/en/src/SUMMARY.md, docs/en/src/borders.md, docs/en/src/configure-key-bindings.md, docs/en/src/filtering.md, docs/en/src/input-operation.md, docs/en/src/layout.md, docs/en/src/message.md, docs/en/src/sorting.md, docs/en/src/style.md, docs/en/src/sum-type.md
So you don't have to learn rust to configure xplr.
=> Document sum types for hackers

.cargo/config, .github/workflows/cd.yml, .github/workflows/ci.yml, .gitignore, Cargo.lock, Cargo.toml, docs/en/src/install.md, docs/en/src/sum-type.md, flake.lock, flake.nix, src/path.rs, src/ui.rs
- Add more build targets
- Allow cross compile (if you have the resources, I don't)
- Fix failing nixos tests
=> Imrove builds

Cargo.lock, Cargo.toml, docs/landing/index.html, src/app.rs, src/init.lua
Also, add global key binding f1.
Also, update deps.
Closes: https://github.com/sayanarijit/xplr/issues/655
=> Display current mode help menu on top

.github/workflows/cd.yml
Fixes: https://github.com/sayanarijit/xplr/issues/662
=> Avoid duplicate strip call

docs/en/src/install.md, src/ui.rs
- Selection indicator in input and logs pane title for people who hide the selection pane.
=> Sync branch

Cargo.lock, Cargo.toml, docs/en/src/awesome-plugins.md, docs/en/src/default-key-bindings.md, docs/en/src/messages.md, flake.lock, src/app.rs, src/cli.rs, src/compat.rs, src/dirs.rs, src/init.lua, src/lua/mod.rs, src/msg/in_/external.rs, src/path.rs, src/ui.rs
- Press `)` to pass `NextVisitedDeepBranch`
- Press `(` to pass `PreviousVisitedDeepBranch`
=> Visit deep level branches

docs/en/src/default-key-bindings.md, docs/en/src/modes.md, src/init.lua
- Press `c` to quickly copy the focused or selected path
- Press `m` to quickly move the focused or selected path
=> Quick copy and quick move

.github/workflows/cd.yml, Cargo.lock, Cargo.toml, docs/en/src/default-key-bindings.md, docs/en/src/modes.md, docs/en/src/upgrade-guide.md, docs/en/src/xplr.util.md, snap/snapcraft.yaml, src/app.rs, src/init.lua, src/lua/mod.rs, src/lua/util.rs, src/ui.rs
- Snap build
- xplr.util.debug()
- `c` and `m` key bindings for quick copy and move.
- ScrollUpHalf fix
- Dependency updates
=> Release v0.21.6

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, docs/en/src/xplr.util.md, src/init.lua, src/lua/mod.rs, src/lua/util.rs
Closes: https://github.com/sayanarijit/xplr/issues/705
Also update xplr version.
=> xplr.util.lscolor shouldn't return nil

src/config.rs, src/lua/util.rs
=> Fix node type resolution

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, docs/script/deploy-cf.sh, src/lua/mod.rs
Fixes: https://github.com/sayanarijit/xplr/issues/718
=> Upgrade deps

docs/en/src/general-config.md, docs/en/src/searching.md, src/app.rs, src/config.rs, src/init.lua, src/msg/in_/external.rs, src/search.rs
Customize search algorithm with:
- xplr.config.general.search.exact_mode
- xplr.config.general.search.rank_builder
Closes: https://github.com/sayanarijit/xplr/issues/678
=> Improve search ranking algorithm
