sayanarijit/xplr

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs
By default, while renaming a file, autocomplete the relative path i.e.
the filename instead of the absolute path in the input buffer.
(In reality, this PR is intended to test the CD pipeline).
=> Autocomplete the relative path while renaming

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/explorer.rs, src/main.rs
Bug:
When you call some command in a directory with a large number of hosts,
xplr will fail setting the environment vars as the command will become
too large to handle.
Fix:
Port the value of multi-line variables from env vars to pipes and set
the name of the pipe as env var instead. And deprecate the variables
that doesn't make much sense.
In other words,
- `$XPLR_APP_YAML` has been removed.
- `$XPLR_RESULT` has been ported to `$XPLR_PIPE_RESULT_OUT`.
- `$XPLR_GLOBAL_HELP_MENU` has been ported to
`$XPLR_PIPE_GLOBAL_HELP_MENU_OUT`.
- `$XPLR_DIRECTORY_NODES` has been ported to
`$XPLR_PIPE_DIRECTORY_NODES_OUT`.
- `$XPLR_LOGS` has been ported to `$XPLR_PIPE_LOGS_OUT`.
- `$XPLR_PIPE_RESULT` has been ported to `$XPLR_PIPE_RESULT_OUT`.
Hence, instead of `<<< $VAR`, `< $VAR_PIPE_OUT` should be …
=> Fix large env vars breaking the subprocess

Cargo.lock, Cargo.toml, src/app.rs, tests/test_version.rs
With this change, `xplr` will only raise version incompatibility error
if the major version changes. Minor version updates are assumed to be
backwards compatible.
If the major version is `v0`, the minor version will be considered as
the major version and the security/patch version will be considered as
minor version and the same logic will apply.
=> Improve version incompatibility error

src/app.rs, src/main.rs
Since users don't need to update config file version for minor app
releases, we have to differentiate between app and config version.
Also, expose them via `$XPLR_CONFIG_VERSION` and `$XPLR_APP_VERSION`.
=> Add XPLR_APP_VERSION and XPLR_CONFIG_VERSION

src/main.rs
Print all the outputs of xplr commands on the alternate screen. Not on
the real stdout.
=> Do not print command outputs to the main screen.

src/config.rs
Also, use `open` to open files when `xdg-open` is missing.
=> Display help menu using $PAGER

Cargo.lock, Cargo.toml, default.nix, src/app.rs, src/config.rs
Concern:
Using `ResetNodeFilters` to clear the filters while searching or exiting
from search unexpectedly resets the `show hidden` mode because the
action not only removes the target filter, it resets all the other
filters as well.
Solution:
Implement `RemoveNodeFilterFromInput` to be able to clear or remove
target filters without having to reset it.
=> Improve search and filter

src/config.rs
Issue:
`esc` is generally used to get back to the `default` mode and mistakenly
pressing `esc` while in `default` mode will annoyingly terminate the
session.
Fix:
Remove `esc` from the `default` mode's key bindings. Use `q` or `crtl-c`
instead.
=> Don't quit on esc

src/config.rs
This might be a little counter intuitive to the `nnn` users, but I think
this will add to the productivity and should be the default.
Since we have a real-time mode indicator, users shouldn't face much of
an issue switching to the alternate default.
=> Stay in search mode when entering or leaving a directory

src/app.rs
[canonicalize()](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) and [metadata()](https://doc.rust-lang.org/std/fs/fn.metadata.html) both resolve symlinks, thus showing symlinks as regular files
By the way, would be nice to be able to show in the UI the destination of the symlink, and potentially also whether symlink leads to a directory or to a file (i.e. can be entered by pressing `l`).
And goes without saying: awesome project!! 🚀
=> Fix symlink support

src/main.rs
Don't depend on `Refresh`, always write to the pipes.
=> Fix logs for being written in the pipe

src/config.rs, src/ui.rs
Example:
```yaml
filetypes:
directory:
custom:
foo: bar
...
```
Where `foo` and `bar` can be anything string.
It can be accessed with the `{{{custom.foo}}}` variable.
=> Add support for custom metadata for table row UI

src/input.rs
Removed comma.
Error was as follows:
error: no rules expected the token `,`
--> src/input.rs:373:29
|
373 |                 | Self::Num9,
|                             ^ no rules expected this token in macro call
error: aborting due to previous error
=> Fixed error preventing compilation

src/app.rs, src/config.rs, src/main.rs
Some commands doesn't require to capture stdout and stderr.
They can be called without needing to reset the screen.
Add `CallSilently` and `BashExecSilently` to execute those commands
faster.
Also, some optimization.
=> Ability to call commands silently

Cargo.lock, Cargo.toml, default.nix, src/app.rs, src/config.rs, src/config.yml, src/main.rs, src/ui.rs
Remapping a key should overwrite default. Also, remapped keys shouldn't
be redundantly visible in help menu.
Also, display log time.
=> Fix remap behaviour and help menu

src/app.rs, src/config.yml
Use `ctrl-i` (tab) and `ctrl-o` to navigate history.
Closes: https://github.com/sayanarijit/xplr/issues/49
=> Add basic history navigation

xplr.desktop
I continue my migration from `nnn`, this is a copy-paste from their repo basically. This allows you to launch `xplr` from a launcher, but also if you have `inode/directory=xplr.desktop` in `~/.config/mimeapps.list` you can just do `xdg-open /path/to/folder` and explore the folder in a new terminal.
cc @orhun once merged, could you please update the pkgs to get this installed to `/usr/share/applications/xplr.desktop`?
We dont have an icon of course, so we can drop `Icon=`, or it can stay (it doesn't hurt) and remind us that an icon is needed 😛 
FYI if you come up with an icon, just put it in the repo, we would need to install the icons to this location and then it will magically work (again this is how nnn does this) 🙂 
```
/usr/share/icons/hicolor/64x64/apps/xplr.png …
```
=> Add desktop file

src/config.yml, src/pwd_watcher.rs
Issue:
$PWD watch service panics when visiting restricted directories.
Fix:
Log error instead of panic.
=> Fix panic on permission denied

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml
Use `gf` to follow symlinks instead of `enter`/`l`.
Or use the message `FollowSymlink`.
=> Fix follow symlink behavior.

src/runner.rs
Now, when you do `xplr > out.txt` and invoke the terminal, the stdout
won't be redirected.
=> Fix terminal output redirection when piping stdout

Cargo.lock, Cargo.toml, src/app.rs
Fix issue where running `xplr /path/to/file` doesn't `cd` into the
parent directory.
=> Fix `cd` on first focus

Cargo.lock, Cargo.toml, README.md, src/app.rs, src/config.rs, src/config.yml, src/default_config.rs, src/input.rs, src/ui.rs
Now, users can change the UI layout via the `SwitchLayout{Builtin|Custom}`
message, or by using key `ctrl-w`.
There are 3 default layout options -
- default
- no_help
- no_selection
- no_help_no_selection
Also, the initial mode and the initial layout can be specified in the
config.
----------
Any layouts will default to `Nothing` which resembles blank screen.
However, they will be overwritten when there is a more specific layout
available either in the super config or in the sub config.
-----------------
- Define layout constraints based on screen size and relative panel
size.
- Define borders.
- Define panel style.
- Define panel title and title style.
--------------
It's difficult to calculate the bits for adding and removing modifiers.
With this commit, we be will use words `Bold`, …
=> Add feature dynamic UI

benches/navigation.rs, src/app.rs, src/runner.rs
From this commit, the app state will be written to the output pipes only
when invoking a command.
For auto refreshing pipes, we can brainstorm on `service`s concept.
=> Don't refresh pipes on every iteration

src/pipe_reader.rs
Do not close the input pipe file after reading. Instead, read it, empty
it, then close it.
=> Read pipes in a safer way.

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml, src/explorer.rs, src/pwd_watcher.rs, src/runner.rs, src/ui.rs
This PR targets 2 pain points.
1. The `Explore` message was async, which caused some unexpected
behavior. This was fixed by splitting `Explore` into `ExplorePwd`,
`ExplorePwdAsync` and `ExploreParentsAsync`. `ExploreParentsAsync`
is similar to the former `Explore`, which is mainly used when loading
`xplr` for the first time. However, what we'll be using frequently
are `ExplorePwd` and `ExplorePwdAsync` messages.
2. Files with spaces caused some unexpected behavior. This was fixed by
escaping the paths properly. This also fixed focusing of a file after
creating or renaming it.
Anothor breaking change is that `XPLR_PIPE_FOCUS_OUT` has been removed.
`XPLR_FOCUS_PATH` is all we need. So, the rule of thumb is if a variable
contains one liner value, it can be used directly from the env vars. …
=> Fix exploring and escaping paths

src/app.rs, src/explorer.rs, src/pwd_watcher.rs, src/runner.rs
```
Benchmarking focus next item: Collecting 100 samples in estimated 5.1972 s (126k itera                                                                                      focus next item         time:   [41.216 us 41.346 us 41.494 us]
change: [-28.669% -28.110% -27.551%] (p = 0.00 < 0.05)
Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
4 (4.00%) high mild
5 (5.00%) high severe
Benchmarking focus previous item: Collecting 100 samples in estimated 5.0576 s (116k i                                                                                      focus previous item     time:   [43.589 us 43.754 us 43.927 us]
change: [-29.506% -28.748% -28.039%] (p = 0.00 < 0.05)
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
1 (1.00%) high mild
2 …
```
=> Optimize performance

src/event_reader.rs, src/pipe_reader.rs, src/runner.rs
- Optimize by avoiding cloning the whole app in each iteration of the main
loop.
- Increase the input poll timeout from 1 to 200. This works because the
poll will not apply to key hold.
- Do not read input pipe if it hasn't been modified.
=> Further optimize performance and CPU usage

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml, src/event_reader.rs, src/ui.rs
Pressing an invalid key will take you to the ~reckless~recover mode. All you
need to do is calm down, escape that mode, and try again.
Closes: #142
=> Add ~reckless~ recover mode

Cargo.lock, Cargo.toml, src/app.rs, src/config.rs, src/config.yml, src/ui.rs
Use `remaps: {key: null}` to un-map a key.
Also,
- `gx` will now open only the file under focus.
- `:sx` will open the selected files.
And other minor improvements.
=> Add support for un-mapping keys.

src/pipe_reader.rs, src/runner.rs
The initial idea was to enable other tools to control `xplr` via the
input pipe. However, so far I didn't feel the need to use this feature.
And even if there is any need, it's much better to implement ad-hoc
services instead of wasting cpu resources.
=> Read input pipe only once when commands execute

Cargo.lock, Cargo.toml, src/app.rs, src/init.lua, src/lua.rs, src/pipe_reader.rs, src/runner.rs
This works:
```lua
xplr.fn.custom.ping = function(app)
print("What's your name?")
local name = io.read()
os.execute('read -p "Hello ' .. name .. ', you are in ' .. app.pwd .. '"')
return {
{ LogSuccess = "pong" },
}
end
```
Then it can be called via `CallLua: custom.ping`.
=> Add CallLua and CallLuaSilently

src/app.rs, src/config.rs, src/init.lua, src/ui.rs
Remaps has been removed to simplify key bindings. With Lua, it's now
possible to remap using basic assignments.
For e.g.
```Lua
xplr.config.modes.builtin.default.key_bindings.on_key["v"] = xplr.config.modes.builtin.default.key_bindings.on_key.space
```
Help menu will auto detect remapped keys and display after removing the
redundant mappings.
Ref: https://github.com/sayanarijit/xplr/discussions/183#discussioncomment-774159
=> Remove "remaps:"

Cargo.lock, Cargo.toml, src/init.lua, src/lua.rs
Unfortunately, "ctrl-i" doesn't work unless "tab" i sremapped to the
key.
=> Fix "ctrl-i" key for history navigation

Cargo.lock, Cargo.toml, src/lua.rs, src/runner.rs, src/ui.rs
Serializing to and from Lua value is expensive. Hence, once serialized,
we should reuse the value.
=> Optimize rendering speed by serializing less

src/app.rs, src/config.rs, src/init.lua, src/runner.rs, src/ui.rs
- Make mouse disabled by default.
- Add key binding `:m` to toggle mouse.
Closes: https://github.com/sayanarijit/xplr/issues/206
=> Disable mouse by default and bind `:m` to toggle

.github/workflows/cd.yml, Cargo.lock, Cargo.toml, src/lua.rs
Many crates are outdated. One is even yanked. IMO failing build is
better than running with insecure/bad dependencies.
Ref: https://github.com/sayanarijit/xplr/issues/212#issuecomment-855175144
=> Remove --locked

examples/run.rs, src/app.rs, src/bin/xplr.rs, src/lib.rs, src/runner.rs
This improves the compatibility and adds the ability to introduce
non-breaking changes by using a builder pattern.
Example:
```rust
fn main() {
match xplr::runner(None).and_then(|a| a.run()) {
Ok(Some(out)) => print!("{}", out),
Ok(None) => {}
Err(err) => {
if !err.to_string().is_empty() {
eprintln!("error: {}", err);
};
std::process::exit(1);
}
}
}
```
=> Further improve the API.

src/app.rs, src/runner.rs
Adds basic support for nnn-like FIFO based previewer.
The FIFO can be manager with the following messages:
- StartFifo: /path/to/fifo
- StopFifo
- ToggleFifo: /path/to/fifo
A basic nnn plugin wrapper example:
```lua
-- nnn_preview_wrapper.lua
-- Usage Example:
--
--   require("nnn_preview_wrapper").setup{
--     plugin_path = os.getenv("HOME") .. "/.config/nnn/plugins/preview-tabbed",
--     fifo_path = "/tmp/xplr.fifo",
--     mode = "action",
--     key = "p",
--   }
--
-- Press `:p` to toggle preview mode.
local function setup(o)
if o.fifo_path == nil then
o.fifo_path = os.getenv("NNN_FIFO")
end
if o.mode == nil then
o.mode = "action"
end
if o.key == nil then
o.key = "p"
end
local enabled = false
local message = nil
os.execute('[ ! -p "' .. o.fifo_path ..'" ] && mkfifo "' .. …
```
=> Add support for fifo based previewer

Cargo.lock, Cargo.toml, benches/criterion.rs, src/app.rs, src/bin/xplr.rs, src/lua.rs, src/runner.rs
Also, add `-c` / `--config` CLI option to specify custom config file.
Priority is:
`-c <PATH>` > `~/.config/xplr/init.lua` > `/etc/xplr/init.lua`.
Fixes: https://github.com/sayanarijit/xplr/issues/230
=> Fix config path on macOS

src/app.rs, src/config.rs, src/init.lua, src/runner.rs
Adds the following messages:
- PrintPwdAndQuit
- PrintFocusPathAndQuit
- PrintSelectionAndQuit
And key bindings:
`:q<enter>` -> Quit.
`:qp` -> PrintPwdAndQuit.
`:qf` -> PrintFocusPathAndQuit.
`:qs` -> PrintSelectionAndQuit.
`:qr` -> PrintResultAndQuit.
Closed: https://github.com/sayanarijit/xplr/issues/257
=> Add more quit options

docs/en/src/install.md
Cool book 😉 
It's maybe not so important, but `-Syu` does a little more than just installing `xplr`, it also updates the local pacman dbs, and it also updates _all_ installed packages on the system. `pacman -S` is a canonical command that does nothing more but installing a package 🙂
=> Update pacman command

src/ui.rs
It helps to see all the logs when switching to a bigger InputAndLogs
layout.
=> Make the number of visible logs dynamic

Cargo.lock, Cargo.toml, src/runner.rs
Termion is only used to get TTY which is simple enough to implement.
=> Remove termion dependency

Cargo.lock, Cargo.toml, benches/criterion.rs, src/app.rs, src/bin/xplr.rs, src/init.lua, src/runner.rs
Use `-C` / `--extra-config` to load Lua files to overwrite the
default or user defined config.
This helps with integration, where integrating xplr with another tool
requires xplr to overwrite some config, without requiring the users to
install an xplr plugin or update the xplr config.
Example:
```bash
xplr -C one.lua two.lua
xplr -C one.lua -C two.lua
```
> **WARNING:**
>
> Extra config doesn't require specifying the `version`, hence, it's the
> integration author or the user's responsibility to assert
> compatibility using the globally exposed `version` in the extra config
> files, similar to xplr plugins.
Ref: https://github.com/sayanarijit/xplr/issues/316
=> Add support for loading extra config files

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/app.rs, src/lua.rs
- Do not log error if config file is missing.
- Fallback to /tmp when runtime path is inaccessible.
Fixes: https://github.com/sayanarijit/xplr/issues/319
=> Config and runtime  path access fixes

examples/run.rs, src/app.rs, src/bin/xplr.rs, src/cli.rs, src/lib.rs, src/runner.rs
I Refactored parts of `runner::Runner` to take a Cli struct, instead of putting everything manually in `Runner`.
This is what you want to use most of the time. Otherwise your stuck with a lot of 
```rs
.and_then(|a| a.yyy(xxx))
```
in `xplr::runner::Runner`.
=> Some refactors

src/app.rs
The `Config` object is globally available as `xplr.config`, and thus
it's redundant. Config is read only once, when xplr loads.
Closes https://github.com/sayanarijit/xplr/issues/321
=> Remove `config` from CallLuaArg

src/event_reader.rs, src/explorer.rs, src/pwd_watcher.rs, src/runner.rs
Wait for confirmation after sending a message to a thread.
Also, use unwrap() to crash and burn than using unwrap_or_default() when
message passing fails.
It's highly unlikely to happen and also trivial to the core logic. But
let's see the error when it does happen.
Fixes https://github.com/sayanarijit/xplr/issues/301
=> Fix reading input

src/ui.rs
Example:
```lua
xplr.config.layouts.builtin.default = {
CustomContent = {
title = "custom title",
body = {
StaticParagraph = { render = "\x1b[31mcustom body\x1b[0m" },
},
},
}
```
=> Support terminal colors in custom layout

src/runner.rs
Silent calls don't need to pause input reading as they are non
interactive and quickly finish execution.
=> Optimize silent calls

Cargo.lock, Cargo.toml, docs/en/src/upgrade-guide.md, src/lua.rs
Upgrade version when just before making a new release, else the doc will
link to invalid release.
=> Downgrade version for the docs

Cargo.lock, Cargo.toml, docs/en/src/general-config.md, docs/en/src/style.md, src/app.rs, src/config.rs, src/init.lua, src/input.rs, src/runner.rs, src/ui.rs
New message: `UpdateInputBufferFromKey` to replace most
`BufferInputFromKey` usage.
This adds more functionalities to the input buffer and reduces
boilerplate code.
This commit also deprecates `config.general.cursor` as the cursor will
be set by the terminal from now.
Repo: https://github.com/sayanarijit/tui-input
=> Use tui-input to handle input buffer

docs/en/src/message.md, src/app.rs, src/input.rs
This PR adds a new message: `UpdateInputBuffer: InputOperation`
This makes it possible to perform cursor based input operations without
needing input from the keyboard.
=> Support more control over input buffer

docs/en/src/message.md, src/app.rs, src/runner.rs
This PR adds support for quickly executing arbitrary lua functions,
without needing to define a function.
Example:
```lua
xplr.config.modes.builtin.default.key_bindings.on_key["#"] = {
help = "test",
messages = {
{ LuaEvalSilently = [[return { { LogInfo = "foo" } }]] },
{ LuaEval = [[return { { LogInfo = io.read() } }]] },
},
}
```
Partly closes: https://github.com/sayanarijit/xplr/issues/394
=> Add support for LuaEval(Silently) messages

src/__cache__.lua, src/app.rs, src/lua.rs, src/pwd_watcher.rs, src/runner.rs, src/ui.rs
Fixes: https://github.com/sayanarijit/xplr/issues/412
=> Fix Lua API performance by caching

docs/en/src/general-config.md, src/config.rs, src/init.lua, src/ui.rs
Motivation: 
I wanted to disable remaps in my config, but I found there is no way of doing that in the latest release, except for removing code.
I've allowed edits, so that if you don't like the naming of the config entry, you can change it.
Now you can do `xplr.config.general.help_hide_remaps = true` to hide all remaps, except one.
=> Introduce `general.hide_remaps_in_help_menu` config entry.

docs/en/src/message.md, src/runner.rs
If the argument of `LuaEval` evaluates to a function, xplr will try to
pass Lua Context to it.
Example:
```lua
{ LuaEval = [[function(app) return { { LogInfo = app.pwd } } end]] }
```
Closes: https://github.com/sayanarijit/xplr/issues/394
=> Support passing argument to `LuaEval` and `LuaEvalSilently`

src/app.rs, src/bin/xplr.rs, src/cli.rs, src/runner.rs
Use `--print-pwd-as-result` to print the last working directory instead
of the focused or selected nodes, when you quit using the `PrintResultAndQuit`
message (i.e. by pressing `enter`).
This helps with implementing the "cd on quit" functionality using a plain shell
alias.
Example:
```
alias xcd='cd "$(xplr --print-pwd-as-result)"'
```
With this alias set, you can navigate directories using xplr by entering
`xcd` command, and when you quit by pressing enter, you will enter the
directory.
You can of course, quit with plain `Quit` (i.e. by pressing `esc`) to
gracefully cancel "cd on quit".
=> CLI for a better "cd on quit"

docs/en/src/general-config.md, src/config.rs, src/ui.rs
This adds support for defining custom border types and border styles.
Example:
```
xplr.config.general.panel_ui.default.border_type = "Thick"
xplr.config.general.panel_ui.default.border_style.fg = "Black"
xplr.config.general.panel_ui.default.border_style.bg = "Gray"
```
Closes: https://github.com/sayanarijit/xplr/issues/448
=> Support custom `border_type` and `border_style`

docs/en/src/debug-key-bindings.md, docs/en/src/general-config.md, src/app.rs, src/config.rs, src/init.lua
- Use `xplr.config.general.global_key_bindings` to define a set of
key bindings that are available by default in every mode. e.g `esc`
and `ctrl-c`.
- Remove boilerplate config from `init.lua`.
- Update docs.
=> Add global key bindings that can be overwritten.

docs/en/src/awesome-hacks.md
Added FreeBSD 13.1-RELEASE to a list of OSes on which the image preview hack and text preview hack were tested on.
I tried both of them, both work as advertised.
=> Added FreeBSD to a list of OSes

Cargo.lock, Cargo.toml, docs/en/src/environment-variables-and-pipes.md, docs/en/src/layout.md, docs/en/src/lua-function-calls.md, docs/en/src/messages.md, docs/en/src/upgrade-guide.md, src/app.rs, src/bin/xplr.rs, src/cli.rs, src/explorer.rs, src/init.lua, src/msg/in_/external.rs, src/runner.rs, src/ui.rs
--vroot helps isolating navigation of an xplr session inside a specific directory. However, interaction still requires passing full paths (`/tmp/vroot`). Shell scripts and Lua functions can still access files outside the virtual root.
This PR also fixes unwanted dot (.) and extra slash (//) issues in paths.
=> Add support for --vroot

docs/en/src/install.md
=> link to header for crates.io install is fixed

Cargo.lock, Cargo.toml, docs/en/src/column-renderer.md, docs/en/src/xplr.util.md, docs/script/generate.py, src/config.rs, src/init.lua, src/lua/util.rs, src/path.rs, src/ui.rs
- Apply style only to the file column in the table.
- Properly quote paths.
- Expose the applicable style from config in the table renderer argument.
- Add utility functions:
- xplr.util.node_type
- xplr.util.style_mix
- xplr.util.shell_escape
=> More UI utilities and improvements

src/lua/util.rs
I was playing around with layout_replace on the current dev branch and noticed replacing layouts like "HelpMenu" was not supported due to the parameter types.
=> Fix layout_replace only working with table parameters

src/app.rs
Also applies to ToggleSelectAll i.e. `ctrl-a`
=> SelectAll: extend selection list rather than replacing

docs/en/src/node_types.md
Add missing comma to node_types lua conf example in the docs.
=> docs: add missing comma to node_types lua conf

docs/en/src/layout.md, src/ui.rs
This adds `CustomLayout` panel for nesting a `Layout` inside the `Static` and `Dynamic` layouts.
This will help switching between different layouts dynamically, without having to switch modes.
=> Allow nesting layouts inside a custom layout

Cargo.lock, Cargo.toml, src/app.rs, src/dirs.rs, src/lib.rs, src/path.rs
Alternative solution to #630 to solve #627.
I created a `dirs.rs` module wrapping xdg and also moved the env::temp_dir() fallback for the runtime dir in there as well, since it seemed like a good fit. If you want we could also move more of the config file finding logic here.
=> Use xdg-rust crate instead of dirs crate

docs/en/src/awesome-plugins.md
mentioning https://gitlab.com/hartan/web-devicons.xplr, which converts nvim-web-devicons to a xplr-compatible format and adds optional colors.
Sidenote: It seems that nvim-web-devicons, when matching for special file names, performs a case-insensitive match. Would you mind having the same feature in xplr? Currently some special files don't get picked up correctly (like `COPYING`) for this reason. If you're fine with that, I'll happily provide a PR for that.
=> docs: Add entry to awesome-plugins

src/app.rs
Silently fail to "Enter" regular files. Entering only makes sense for directories.
This fixes https://github.com/sayanarijit/xplr/issues/653#issue-1806818324
I don't know Rust at all, so I make no claims to the code quality. But I have tested this change and it does work.
=> Silently fail to 'enter' regular files

src/init.lua
When passing arguments to `xargs` binaries can only be used, we cannot use a shells builtin command, so this issue cannot be subverted just by installing bash. In this instance, my systems `printf` implementation does not support the `%q` format specification—specifically a GNU extension. Yielding this error upon trying to delete a file:
```shell
printf: illegal format character q
```
For a more visual example;
```
navi:~
% uname ; man 1 printf | grep '%q' | wc -l
FreeBSD
0
navi:~
% printf "%q\n" \f \oo 'bar'* baz
printf: illegal format character q
navi:~
% bash -c 'printf "%q\n" \f \oo 'bar'* baz '
f
oo
bar\*
baz
```
Remedying this is just a case of not using `xargs` and instead iterating through each line of the output pipe, then calling bash's builtin `printf` (oppose to an actual …
=> init: Fix error upon deleting file on non-GNU systems

docs/en/src/install.md
=> Update Arch Linux package URL in install.md

Cargo.lock, Cargo.toml
which apparently causes custom styling to be lost on the currently selected line.
I noticed that the last version increase contained a bunch of dependency updates (#700). One of the updated dependencies was `ansi-to-tui`, which had a major version increase from 3 to 4. Unfortunately [their Changelog][1] isn't up to date, but in the Git history I found [this commit][2] which, as far as I can tell, changes [the handling of the reset ANSI code][3], probably justifying the major version increase.
Before the update (or with this patch applied), my active line looks like this: 
whereas with the current version, I get this:
As far as I can tell this change was introduced in 9db8b2cc190c98e532cf511cc9c1b39663f1343b, but at a quick glance I don't see an immediate connection between the code added …
=> cargo: Revert version update on `ansi-to-tui`

Cargo.toml
useful for distros  
---
no change in default behaviour, but allows passing `--no-default-features` which makes mlua look up luajit via pkg-config to link to a system library. distros already patch this, so this lets them do it with no patch :)
=> cargo: allow building with system lua

benches/criterion.rs, docs/en/src/general-config.md, src/app.rs, src/config.rs, src/directory_buffer.rs, src/init.lua, src/runner.rs, src/ui.rs
- Added through a setting `vimlike_scrolling` which is turned off by default
- A hard-coded _(for now)_ cushion of `5` lines that allows for previewing the next lines while scrolling
- A separate struct `ScrollState` with getters and setters for the `current_focus` field to disallow setting the field without updating the `last_focus` field
=> Adds Vim-Like Scrolling to XPLR

src/init.lua
This PR fixes issue #736 by adding a check for empty user input when tab completing a path (`src/init.lua` : `try_complete_path`)
Fix has been tested on multiple systems, does not interfere with other functionality.
=> Fix crash when tab completing an empty string (#736)

Cargo.lock, Cargo.toml
This fixes the build on s390x, because nix 0.24 isn't used anymore.
A newer version of skim (0.20) is available, but it conflicts with ratatui.
=> Update skim to 0.18

src/lua/mod.rs
allow reading non-utf8 init files and not error on loading bytecode.
note: the benefits in startup time are minimal.
=> allow reading of luajit bytecode as init files
